language: python

python:
  - "2.7"
  - "3.4"

env:
  - NODE_VERSION="10.7"

before_install:
  - sudo apt-get update -yqq
  - nvm install $NODE_VERSION

install:
  - npm install -g ajv-cli
  - pip install -r requirements.txt

before_script:
  - pylint --errors-only ./testing

script:
  - ./scripts/lint-json-dirs
  - pre-commit run --all-files --verbose
  - pytest
  - ajv compile -s "schema/*.json" -r "schema/*.json"
  - ajv validate -s schema/format.json -d "examples/fmt-*.json" -r "schema/*.json"
  - ajv validate -s schema/tool.json -d "examples/md5*.json" -r "schema/*.json"
  - ajv validate -s schema/business-rule.json -d "examples/br-*.json" -r "schema/*.json"
